-- Create a table for user logs
create table if not exists public.user_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid not null,
  title text,
  description text,
  device_ip text,
  request_url text,
  request_param text,
  state text
);

-- Enable Row Level Security (RLS)
alter table public.user_log enable row level security;

-- Create a policy that allows users to select only their own logs
create policy "Users can view their own logs"
on public.user_log
for select
using (auth.uid() = user_id);

-- Create a policy that allows the service_role (which the API might act as, or insert on behalf of user) to insert
-- OR if the API inserts with the user's JWT, we need insert policy.
-- Since the requirement says "For all api endpoints there should be a inserted a row",
-- and the API validates the JWT, the insertion will happen in the backend.
-- The backend (Spring Boot) will likely connect to the DB using a connection string.
-- If it uses the postgres user (service_role), it bypasses RLS.
-- If it uses an authenticated user context (unlikely for direct JDBC), it needs policy.
-- Standard Spring Boot JPA connects as a specific DB user.
-- Usually, we connect as 'postgres' or a dedicated service user which has admin rights or specific grants.
-- So RLS is mostly for direct Supabase client access, but good to have.
